commerce/urls.py
from django.urls import path
from commerce import views as commerce_v

app_name = 'commerce'
urlpatterns = [
    path('commerce/', commerce_v.product_list, name='product_list'),
    path('commerce/product_list/<int:pk>/', commerce_v.detail_product, name='detail_product'),
    path('commerce/product_list/<pk>/remove/', commerce_v.product_remove, name='product_remove'),
    path('commerce/product_list/<int:pk>/edit/', commerce_v.product_edit, name='product_edit'),
    path('commerce/register_product/', commerce_v.product_register, name='product_register'),
    path('commerce/register_order/', commerce_v.register_order, name='register_order'),
    path('commerce/order_list/', commerce_v.order_list, name='order_list'),
    path('commerce/order_list/<int:pk>/', commerce_v.order_detail, name='order_detail'),
    path('commerce/order_list/<int:pk>/edit/', commerce_v.order_edit, name='order_edit'),
    path('commerce/order_list/<int:pk>/remove/', commerce_v.order_remove, name='order_remove'),
]

core/urls.py
from django.urls import path
from core import views as core_v


urlpatterns = [
    path('', core_v.home, name='home'),
]

star_wars_ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('core.urls')),
    path('', include('register.urls')),
    path('', include('commerce.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

commerce/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.conf import settings
from cloudinary.models import CloudinaryField


class Product(models.Model):
    """Model of the products being sold"""
    product_name = models.CharField("Product", max_length=100, blank=False, null=False)
    unit_price = models.FloatField("Unit Price (R$)", validators=[MinValueValidator(10.0), MaxValueValidator(10000000.0)], blank=False, null=False)
    multiple = models.IntegerField("Multiple", default=1, validators=[MinValueValidator(1)], null=False, blank=False)
    image = CloudinaryField('image')
    published_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Product'
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.product_name

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, unique=False)
    product_name = models.ForeignKey(Product, unique=False, on_delete=models.CASCADE)
    suggested_price = models.FloatField("Suggested Price (R$)", validators=[MinValueValidator(10.0), MaxValueValidator(10000000.0)], blank=False, null=False)
    amount = models.IntegerField("Amount", default=1, null=True, blank=True)
    published_date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name = 'Order'
        verbose_name_plural = 'Orders'

    def __str__(self):
        return str(self.user.first_name) + ' -> ' + str(self.product_name)

commerce/forms.py
from django import forms
from django.forms import ModelForm
from .models import Product, Order
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _


class ProductForm(ModelForm):
    """Register products from Product Models"""
    class Meta:
        model = Product
        fields = "__all__"

class OrderForm(ModelForm):
    """Register products ordem from Order Models"""
    class Meta:
        model = Order
        fields = ['product_name', 'suggested_price', 'amount']

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data['amount']
        suggested_price = cleaned_data['suggested_price']
        multiple = cleaned_data['product_name'].multiple
        unit_price = cleaned_data['product_name'].unit_price
        if amount % multiple:
            raise ValidationError(_("Quantity %(amount)s is not multiple of %(multiple)s"),
                params={"amount": amount, "multiple": multiple},
                code="invalid_amount_value",
                )
        if not (suggested_price > unit_price * 0.9):
            raise ValidationError(_("Suggested Price %(suggested_price)s is less than 90 %% of Unit Price %(unit_price)s."),
                params={"suggested_price": suggested_price, "unit_price": unit_price},
                code="invalid_suggested_price_value",
                )

commerce/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
from .models import Product, Order
from .forms import ProductForm, OrderForm
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from cloudinary.forms import cl_init_js_callbacks      

@login_required
def product_list(request):
    """Product List"""
    products = Product.objects.all()
    return render(request, 'commerce/product_list.html', {"products": products})

@login_required
def order_list(request):
    """Order List"""
    orders = Order.objects.filter(user=request.user)
    return render(request, 'commerce/order_list.html', {"orders": orders})

@login_required
def detail_product(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, 'commerce/product_detail.html', {'product': product})

@login_required
def order_detail(request, pk):
    """Order detail"""
    order = get_object_or_404(Order, pk=pk)
    return render(request, 'commerce/order_detail.html', {'order': order})

@staff_member_required
def product_edit(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.published_date = timezone.now()
            product.save()
            return redirect('commerce:detail_product', pk=product.pk)
        else:
            messages.error(request, 'Invalid Values.')
            return render(request, 'commerce/product_edit.html', {'form': form})
    else:
        form = ProductForm(instance=product)
    return render(request, 'commerce/product_edit.html', {'form': form})


@staff_member_required
def product_register(request):
    """Register Products"""
    if request.method == 'POST':
        return _create_product(request)
    else:
        return _new_product(request)

def _create_product(request):
    form = ProductForm(request.POST, request.FILES)
    if not form.is_valid():
        return render(request, 'commerce/product_register.html', {'form': form})
    product = form.save(commit=False)
    product.user = request.user
    product.save()
    messages.success(request, 'You have successfully registered a product!')
    return redirect('commerce:product_register')

def _new_product(request):
    form = ProductForm()
    return render(request, 'commerce/product_register.html', {'form': form})

@staff_member_required
def product_remove(request, pk):
    """Remove product"""
    product = get_object_or_404(Product, pk=pk)
    name = product.product_name
    product.delete()
    messages.success(request, f'The product:{name} has been deleted successfully.')
    return redirect('commerce:product_list')

@login_required
def register_order(request):
    """Product Orders"""
    if request.method == 'POST': 
        return _create_order(request)
    else:
        return _new_order(request)

def _create_order(request):
    form = OrderForm(request.POST)
    if not form.is_valid():
        messages.error(request, 'An error occurred in your order register.')
        return render(request, 'commerce/register_order.html', {'form': form})
    order = form.save(commit=False)
    order.user = request.user
    order.save()
    messages.success(request, 'You have successfully registered order from the product!')
    return redirect('commerce:register_order')
    
def _new_order(request):
    form = OrderForm()
    return render(request, 'commerce/register_order.html', {'form': form})


@login_required
def order_edit(request, pk):
    """Edit Order"""
    order = get_object_or_404(Order, pk=pk)
    if request.method == 'POST':
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.published_date = timezone.now()
            order.save()
            messages.success(request, 'You have successfully updated order from the product!')
            return redirect('commerce:order_detail', pk=order.pk)
        else:
            return render(request, 'commerce/order_edit.html', {'form': form})
    else:
        form = OrderForm(instance=order)
    return render(request, 'commerce/order_edit.html', {'form': form})

@login_required
def order_remove(request, pk):
    """Remove Order"""
    order = get_object_or_404(Order, pk=pk)
    name = order.product_name
    order.delete()
    messages.success(request, f'The order of the product:{name} has been deleted successfully.')
    return redirect('commerce:order_list')

commerce/templates/commerce/order_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <h2>Detail Order</h2>
</div>
<div class="content mt-1 mb-5">
    <div class="card bg-light text-dark">
        <div class="card-header">{{ order.product_name }}</div>
        <div class="card-body">
            <ul><li>Suggested Price: {{ order.suggested_price }}</li>
                <li>Amount: {{ order.amount }}</li>
            </ul>
            <img src="{{ order.product_name.image.url }}" class="img-thumbnail"></div>
        </div>
        <div class="card-footer">
            <a class="btn btn-outline-info" href="{% url 'commerce:order_edit' pk=order.pk %}">Update</a>
            <a class="btn btn-outline-info" href="{% url 'commerce:order_remove' pk=order.pk %}">Remove</a> 
        </div>
</div>
{% endblock %}

commerce/templates/commerce/order_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5">
    <h2><p>Use the bellow form to update order.</p></h2>
</div>
<div class="mt-5">
    <form class="forms" action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.suggested_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.amount|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Finish Update">
    </form>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.errors %}
        <strong>{{ form.non_field_errors }}</strong>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

commerce/templates/commerce/order_list.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <h2>Welcome to Order Page!</h2>
</div>
<div class="content mt-1">
    {% if orders %}
        {% for o in orders %}
        <div class="card bg-light text-dark">
            <div class="card-header"><a href="{% url 'commerce:order_detail' pk=o.pk %}">{{ o.product_name }}</a></div>
            <div class="card-body">Suggested Price: {{ o.suggested_price }}</div>
            <div class="card-body"><img src="{{ o.product_name.image.url }}" class="img-thumbnail"></div>
            <div class="card-footer">Amount: {{ o.amount }}</div>
        </div> 
        {% endfor %}
    {% else %}
    <div class="alert alert-info" role="alert">
        There is no order registered!
      </div>
    {% endif %}
</div>
{% endblock %}

commerce/templates/commerce/product_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <h2>Detail Product</h2>
</div>
<div class="content mt-1 mb-5">
    <div class="card bg-light text-dark">
        <div class="card-header">{{ product.product_name }}</div>
        <div class="card-body"><ul><li>Price: {{ product.unit_price }}</li><li>Multiples: {{ product.multiple }}</li></ul></div>
        <div class="card-footer"><a href="{% url 'commerce:register_order' %}"><button class="btn btn-success">Buy</button></a></div>
        {% if user.is_superuser %}
        <div class="card-footer">
            <a class="btn btn-outline-info" href="{% url 'commerce:product_edit' pk=product.pk %}">Update</a>
            <a class="btn btn-outline-info" href="{% url 'commerce:product_remove' pk=product.pk %}">Remove</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

commerce/templates/commerce/product_edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5">
    <h2><p>Use the bellow form to update products.</p></h2>
</div>
<div class="mt-5">
    <form class="forms" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.unit_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.multiple|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.image|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Finish Update">
    </form>
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
    {% for error in form.errors %}
        <strong>{{ form.non_field_errors }}</strong>
    {% endfor %}
    </div>
    {% endif %}
</div>
{% endblock %}

commerce/templates/commerce/product_list.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <h2>Welcome to Commerce Page!</h2>
</div>
<div class="content mt-1 mb-5">
    {% if products %}
        {% for p in products %}
        <div class="card bg-light text-dark">
            <div class="card-header"><a href="{% url 'commerce:detail_product' pk=p.pk %}">{{ p.product_name }}</a></div>
            <div class="card-body">Price: {{ p.unit_price }}</div>
            <div class="card-body"><img src="{{ p.image.url }}" class="img-thumbnail"></div>
        </div>
        {% endfor %}
    {% else %}
    <div class="alert alert-info" role="alert">
        There is no product registered!
      </div>
    {% endif %}
</div>
{% endblock %}

commerce/templates/commerce/product_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5">
    <h2>Welcome to Orders Page!</h2>
</div>
<div class="content mt-1">
    <form class="forms" action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.suggested_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.amount|as_crispy_field }}
            </div>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.errors %}
            <strong>{{ form.non_field_errors }}</strong>
        {% endfor %}
        </div>
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Finish Order">
    </form>
</div>
{% endblock %}

commerce/templates/commerce/product_register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load cloudinary %}
{% block content %}
<div class="mt-5">
    <h2><p>Use the bellow form to register products.</p></h2>
</div>
<div class="mt-5">
    <form class="forms" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.unit_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.multiple|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.image|as_crispy_field }}
            </div>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.errors %}
            <strong>{{ form.non_field_errors }}</strong>
        {% endfor %}
        </div>
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Finish Signup">
    </form>
</div>
{% endblock %}

commerce/templates/commerce/register_order.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5">
    <h2>Welcome to Orders Page!</h2>
</div>
<div class="content mt-1">
    <form class="forms" action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.suggested_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.amount|as_crispy_field }}
            </div>
        </div>
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for error in form.errors %}
            <strong>{{ form.non_field_errors }}</strong>
        {% endfor %}
        </div>
        {% endif %}
        <input type="submit" class="btn btn-primary" value="Finish Order">
    </form>
</div>
{% endblock %}

commerce/templates/commerce/register_product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="mt-5">
    <h2><p>Use the bellow form to register products.</p></h2>
</div>
<div class="mt-5">
    <form class="forms" action="" method="POST">
        {% csrf_token %}
        <div class="row">
            <div class="col-6">
                {{ form.product_name|as_crispy_field }}
            </div>
            <div class="col-6">
                {{ form.unit_price|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-6">
                {{ form.multiple|as_crispy_field }}
            </div>
        </div>
        <input type="submit" class="btn btn-primary" value="Finish Signup">
    </form>
</div>
{% endblock %}

commerce/templates/commerce/update_product.html
{% extends 'base.html' %}
{% block content %}
<div class="mt-5">
    <h2>Product Detail</h2>
</div>
<div class="content mt-1 mb-5">
    {% for p in object_list %}
    <div class="card bg-light text-dark">
        <div class="card-header">{{ p.product_name }}</div>
        <div class="card-body">Price: {{ p.unit_price }}</div>
        <div class="card-footer"><a href="{% url 'commerce:product_order' %}"><button class="btn btn-success">Buy</button></a></div>
    </div>
    {% endfor %}
</div>
{% endblock %}