commerce/urls.py
from django.urls import path
from commerce import views as commerce_v

app_name = 'commerce'
urlpatterns = [
    path('commerce/', commerce_v.product_list, name='product_list'),
    path('commerce/product_list/<int:pk>/', commerce_v.detail_product, name='detail_product'),
    path('commerce/product_list/<pk>/remove/', commerce_v.product_remove, name='product_remove'),
    path('commerce/product_list/<int:pk>/edit/', commerce_v.product_edit, name='product_edit'),
    path('commerce/register_product/', commerce_v.product_register, name='product_register'),
    path('commerce/register_order/', commerce_v.register_order, name='register_order'),
    path('commerce/order_list/', commerce_v.order_list, name='order_list'),
    path('commerce/order_list/<int:pk>/', commerce_v.order_detail, name='order_detail'),
    path('commerce/order_list/<int:pk>/edit/', commerce_v.order_edit, name='order_edit'),
    path('commerce/order_list/<int:pk>/remove/', commerce_v.order_remove, name='order_remove'),
]

core/urls.py
from django.urls import path
from core import views as core_v


urlpatterns = [
    path('', core_v.home, name='home'),
]

star_wars_ecommerce/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('', include('core.urls')),
    path('', include('register.urls')),
    path('', include('commerce.urls')),
    path('admin/', admin.site.urls),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index.html')
# Create your views here.

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--css-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!--Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <!--Fontawesome-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"></script>
    <title>Star Wars Commerce</title>
</head>
<body>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <a class="navbar-brand" href="{% url 'home' %}">Star Wars ECommerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'commerce:product_list' %}">Product List</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'commerce:product_register' %}">Register Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'commerce:register_order' %}">Register Order</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'commerce:order_list' %}">Order List</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">SignUp</a>
        </li>
      </ul>
    </div>  
  </nav>
  <br>
  <!--aqui-->
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-8">
          {% block content %}
          {% endblock %}
          <!--messages-->
          {% if messages %}
          {% for msg in messages %}
          {% if msg.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
          <div class="alert alert-danger" role="alert">
              <div>
                  <p>{{ msg }}</p>
              </div>
          </div>
          {% endif %}
          {% if msg.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
          <div class="alert alert-success" role="alert">
              <div>
                  <p>{{ msg }}</p>
              </div>
          </div>
          {% endif %}
          {% endfor %}
          </div>
          {% endif %}
          <!--end messages-->
        </div>
      </div>
    </div>
</body>
</html>

core/templates/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<div class="mt-5">
    <div class="float-left"><h2>Welcome to Home Page!</h2></div>
    <div class="logo-image">
        <img src="{% static 'img/Star-Wars-Logo.png' %}" class="rounded mx-auto d-block img-fluid" alt="logo"/>
    </div>
</div>
{% endblock %}